# Generated by Django 6.0.1 on 2026-01-11 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_score', models.IntegerField()),
                ('parking_score', models.IntegerField()),
                ('signal_score', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('decision', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=4)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_score', to='test_sessions.drivingtestsession')),
            ],
        ),
    ]
